development:
    bucket: <%=ENV['AWS_BUCKET_NAME']%>
    access_key: <%=ENV['AWS_ACCESS_KEY']%>
    secret_key: <%=ENV['AWS_SECRET_KEY']%>
production:
    bucket: <%=ENV['AWS_BUCKET_NAME']%>
    access_key: <%=ENV['AWS_ACCESS_KEY']%>
    secret_key: <%=ENV['AWS_SECRET_KEY']%>